export default {
    image1: require("../assets/images/hotelImages/image1.JPG"),
    image2: require("../assets/images/hotelImages/image2.JPG"),
    image3: require("../assets/images/hotelImages/image3.JPG"),
    image4: require("../assets/images/hotelImages/image4.JPG"),
    image5: require("../assets/images/hotelImages/image5.JPG"),
    image6: require("../assets/images/hotelImages/image6.JPG"),
    image7: require("../assets/images/hotelImages/image7.JPG"),
    image8: require("../assets/images/hotelImages/image8.JPG"),
    image9: require("../assets/images/hotelImages/image9.JPG"),
    image10: require("../assets/images/hotelImages/image10.JPG"),
    image11: require("../assets/images/hotelImages/image11.JPG"),
    image12: require("../assets/images/hotelImages/image12.JPG"),
    image13: require("../assets/images/hotelImages/image13.JPG"),
    image14: require("../assets/images/hotelImages/image14.JPG"),
    image15: require("../assets/images/hotelImages/image15.JPG"),
    image16: require("../assets/images/hotelImages/image16.JPG"),
    image17: require("../assets/images/hotelImages/image17.JPG"),
    image18: require("../assets/images/hotelImages/image18.JPG"),
    image19: require("../assets/images/hotelImages/image19.JPG"),
    image20: require("../assets/images/hotelImages/image20.JPG"),
}